name: Node.js CI

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.15.3]

    steps:
    - name: Checkout code
      uses: actions/checkout@v1
    - name: NPM install
      uses: bahmutov/npm-install@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    # Needs to be before the try build step since it prunes dependencies
    - name: Test
      run: npm test
      env:
        CI: true
    - name: Build and package
      run: npm run build:package
      env:
        REDERLY_PACKAGER_ARCHIVE: false
        # Can't preserve packages because try build will find the node module in the parent directory
        REDERLY_PACKAGER_PRESERVE_NODE_MODULES: false
        CI: false # TODO Linting errors cause the build to fail when CI is true (default)
    - name: Try build
      run: npm --prefix build run cli:built noop
      env:
        DB_SYNC: false
        FAIL_ON_MISSING_CONFIGURATIONS: false
